# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='pw_hash',
            field=models.CharField(max_length=256),
        ),
    ]
